{% set name = "Quart" %}
{% set version = "0.16.2" %}
{% set sha256 = "356f4fd795fbf5a7a97bdeb7ca908b5051d0e6e4c0499b2b7c30b743a6938a7e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - quart=quart.cli:main

requirements:
  host:
    - pip
    - python >=3.7.0
    - setuptools >=40.6.2
    - poetry-core >=1.0.0

  run:
    - python >=3.7.0
    - aiofiles >=0.4.0
    - blinker >=1.4
    - click >=7.0
    - hypercorn >=0.11.2
    - itsdangerous >=1.1.0
    - jinja2 >=2.10
    - toml
    - typing_extensions  # TODO: Remove for py>=38
    - werkzeug >=2.0.0

test:
  imports:
    - quart
  commands:
    - quart --version

about:
  home: https://gitlab.com/pgjones/quart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python ASGI web microframework with the same API as Flask
  description: |
    Quart is a Python ASGI web microframework. It is intended to provide the easiest way to use
    asyncio functionality in a web context, especially with existing Flask
    apps. This is possible as the Quart API is a superset of the Flask API.
    Quart aims to be a complete web microframework, as it supports
    HTTP/1.1, HTTP/2 and websockets. Quart is very extendable and has a
    number of known extensions and works
    with many of the Flask extensions.
  doc_url: https://pgjones.gitlab.io/quart/
  dev_url: https://gitlab.com/pgjones/quart

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
